# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apk add busybox-extras
echo "########################"
SCRIPT

Vagrant.configure("2") do |config|
config.vm.define "alpine" do |alpine|
  alpine.vm.hostname = "alpine"
  alpine.vm.box = "alpine/alpine64"
  alpine.vm.provision "shell", inline: $script
  alpine.vm.network "forwarded_port", guest: 80, host: 9090
  alpine.vm.synced_folder ".", "/var/www"
  end
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 1
  end
end
