# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update; apt-get install -y curl docker.io nginx apache2-utils
echo -n "starting..."
curl -sLSf https://github.com/containerd/containerd/releases/download/v1.3.2/containerd-1.3.2.linux-amd64.tar.gz > /tmp/containerd.tar.gz 
tar -xvf /tmp/containerd.tar.gz -C /usr/local/bin/ --strip-components=1
curl -SLfs https://raw.githubusercontent.com/containerd/containerd/v1.3.2/containerd.service | tee /etc/systemd/system/containerd.service
systemctl daemon-reload && systemctl start containerd
systemctl enable containerd
/sbin/sysctl -w net.ipv4.conf.all.forwarding=1
mkdir -p /opt/cni/bin
curl -sSL https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-linux-amd64-v0.8.5.tgz | tar -xz -C /opt/cni/bin
mkdir -p /go/src/github.com/openfaas/
cd /go/src/github.com/openfaas/ && git clone https://github.com/openfaas/faasd
curl -fSLs "https://github.com/openfaas/faasd/releases/download/0.8.2/faasd" --output "/usr/local/bin/faasd" && chmod a+x "/usr/local/bin/faasd"
cd /go/src/github.com/openfaas/faasd/ && /usr/local/bin/faasd install
systemctl status -l containerd --no-pager
journalctl -u faasd-provider --no-pager
systemctl status -l faasd-provider --no-pager
systemctl status -l faasd --no-pager
curl -sSLf https://cli.openfaas.com | sh
sleep 5 && journalctl -u faasd --no-pager
usermod -aG docker vagrant
password=$(cat /var/lib/faasd/secrets/basic-auth-password)
echo "export password=${password}" >> /home/vagrant/.bashrc
rm /etc/update-motd.d/*
echo "setup nginx"
cat << 'EOF' > /etc/nginx/sites-enabled/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location /api {
           auth_basic "Restricted"; 
           auth_basic_user_file /etc/nginx/.htpasswd;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_pass http://127.0.0.1:8080/function;
       }
        location / {
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_pass http://127.0.0.1:8080;
       }
        location /api/echo {
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_pass http://127.0.0.1:8080/function/echo;
       }
         # Error responses
         error_page 404 = @400;         # Invalid paths are treated as bad requests
         proxy_intercept_errors on;     # Do not send backend errors to the client
         default_type application/json; # If no content-type then assume JSON

         error_page 400 = @400;
         location @400 { return 400 '{"status":400,"message":"Bad request"}\n'; }

         error_page 401 = @401;
         location @401 { return 401 '{"status":401,"message":"Unauthorized"}\n'; }

         error_page 403 = @403;
         location @403 { return 403 '{"status":403,"message":"Forbidden"}\n'; }

         error_page 404 = @404;
         location @404 { return 404 '{"status":404,"message":"Resource not found"}\n'; }

         error_page 405 = @405;
         location @405 { return 405 '{"status":405,"message":"Method Not Allowed"}\n'; }
}
EOF

service nginx restart

cat << 'EOF' > /etc/motd
####################################################################################################
ToDo: https://www.openfaas.com/ https://github.com/openfaas/faasd

sudo cat /var/lib/faasd/secrets/basic-auth-password | /usr/local/bin/faas-cli login --password-stdin
docker login

faas new --lang dockerfile example --prefix dockerHubUserName
faas up -f example.yml

sudo htpasswd -c /etc/nginx/.htpasswd admin
Web Admin http://127.0.0.1:8080/ui/ 
>admin sudo cat /var/lib/faasd/secrets/basic-auth-password
curl http://admin:$password@127.0.0.1:8080/system/scale-function/example -d '{\"serviceName\":\"example\", \"replicas\": 0}'
EOF
cat /etc/motd
SCRIPT

Vagrant.configure("2") do |config|
config.vm.define "faasd" do |faasd|
  faasd.vm.hostname = "faasd"
  faasd.vm.box = "ubuntu/bionic64"
  faasd.vm.provision "shell", inline: $script
  faasd.vm.network "forwarded_port", guest: 80, host: 8080
  end
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 1
  end
end
