# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update; apt-get install -y curl docker.io
echo -n "starting..."
curl -sLSf https://github.com/containerd/containerd/releases/download/v1.3.2/containerd-1.3.2.linux-amd64.tar.gz > /tmp/containerd.tar.gz 
tar -xvf /tmp/containerd.tar.gz -C /usr/local/bin/ --strip-components=1
curl -SLfs https://raw.githubusercontent.com/containerd/containerd/v1.3.2/containerd.service | tee /etc/systemd/system/containerd.service
systemctl daemon-reload && systemctl start containerd
systemctl enable containerd
/sbin/sysctl -w net.ipv4.conf.all.forwarding=1
mkdir -p /opt/cni/bin
curl -sSL https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-linux-amd64-v0.8.5.tgz | tar -xz -C /opt/cni/bin
mkdir -p /go/src/github.com/openfaas/
cd /go/src/github.com/openfaas/ && git clone https://github.com/openfaas/faasd
curl -fSLs "https://github.com/openfaas/faasd/releases/download/0.8.2/faasd" --output "/usr/local/bin/faasd" && chmod a+x "/usr/local/bin/faasd"
cd /go/src/github.com/openfaas/faasd/ && /usr/local/bin/faasd install
systemctl status -l containerd --no-pager
journalctl -u faasd-provider --no-pager
systemctl status -l faasd-provider --no-pager
systemctl status -l faasd --no-pager
curl -sSLf https://cli.openfaas.com | sh
sleep 5 && journalctl -u faasd --no-pager
usermod -aG docker vagrant
password=$(cat /var/lib/faasd/secrets/basic-auth-password)
echo "export password=${password}" >> /home/vagrant/.bashrc
rm /etc/update-motd.d/*
cat << 'EOF' > /etc/motd
####################################################################################################
ToDo: https://www.openfaas.com/ https://github.com/openfaas/faasd

sudo cat /var/lib/faasd/secrets/basic-auth-password | /usr/local/bin/faas-cli login --password-stdin
docker login

export OPENFAAS_URL=http://127.0.0.1:8080
faas new --lang dockerfile example --prefix dockerHubUserName
faas up -f example.yml

Web Admin http://127.0.0.1:8080/ui/ admin sudo cat /var/lib/faasd/secrets/basic-auth-password
curl http://admin:$password@127.0.0.1:8080/system/scale-function/example -d '{\"serviceName\":\"example\", \"replicas\": 0}'
EOF
cat /etc/motd
SCRIPT

Vagrant.configure("2") do |config|
config.vm.define "faasd" do |faasd|
  faasd.vm.hostname = "faasd"
  faasd.vm.box = "ubuntu/bionic64"
  faasd.vm.provision "shell", inline: $script
  faasd.vm.network "forwarded_port", guest: 8080, host: 8080
  end
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 1
  end
end
