# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update; apt-get install -y shellcheck curl postgresql postgresql-contrib

#cat << 'EOF' > /etc/postgesSQL/elasticsearch.yml
#network.host: 0.0.0.0
#cluster.name: myCluster1
#node.name: "myNode1"
EOF
SCRIPT

Vagrant.configure("2") do |config|
config.vm.define "postgesSQL" do |postgesSQL|
  postgesSQL.vm.hostname = "postgesSQL"
  postgesSQL.vm.box = "ubuntu/bionic64"
  postgesSQL.vm.provision "shell", inline: $script
  postgesSQL.vm.network "forwarded_port", guest: 5432, host: 5432
  postgesSQL.vm.synced_folder ".", "/var/www/html"
  end
config.vm.provider "virtualbox" do |v|
  v.memory = 2048
  v.cpus = 2
  end
end
