# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update; apt-get install -y shellcheck curl
# for debian systems, installs dokku via apt-get
wget https://raw.githubusercontent.com/dokku/dokku/v0.17.9/bootstrap.sh
DOKKU_TAG=v0.17.9 bash bootstrap.sh
# go to your server's IP and follow the web installer
SCRIPT

Vagrant.configure("2") do |config|
config.vm.define "dokku" do |dokku|
  dokku.vm.hostname = "dokku"
  dokku.vm.box = "ubuntu/bionic64"
  dokku.vm.provision "shell", inline: $script
  dokku.vm.network "forwarded_port", guest: 80, host: 8090
  dokku.vm.synced_folder ".", "/var/www/html"
  end
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
  end
end
