# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.define "prometheus" do |prometheus|
  prometheus.vm.hostname = "Prometheus"
  prometheus.vm.box = "ubuntu/bionic64"
  prometheus.vm.provision "shell", path: "bootstrap.sh"
  prometheus.vm.network "forwarded_port", guest: 9090, host: 9999
  prometheus.vm.network "forwarded_port", guest: 3000, host: 3000
  #prometheus.vm.synced_folder ".", "/"
  end 
config.vm.provider "virtualbox" do |v| 
  v.memory = 2048
  v.cpus = 2 
  end 
end   
