# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.define "prometheus" do |prometheus|
  prometheus.vm.hostname = "prometheus"
  prometheus.vm.box = "ubuntu/bionic64"
  prometheus.vm.provision "shell", path: "bootstrap-prometheus.sh"
  prometheus.vm.network "forwarded_port", guest: 9090, host: 9999
  prometheus.vm.network "forwarded_port", guest: 3000, host: 3000
  prometheus.vm.network "private_network", ip: "10.0.20.1"
  #prometheus.vm.synced_folder ".", "/"
  end 
config.vm.define "node01" do |node01|
  node01.vm.hostname = "node01"
  node01.vm.box = "ubuntu/bionic64"
  node01.vm.provision "shell", path: "bootstrap-node.sh"
  node01.vm.network "private_network", ip: "10.0.20.2"
  #node01.vm.synced_folder ".", "/"
  end 
config.vm.define "node02" do |node02|
  node02.vm.hostname = "node02"
  node02.vm.box = "ubuntu/bionic64"
  node02.vm.provision "shell", path: "bootstrap-node.sh"
  node02.vm.network "private_network", ip: "10.0.20.3"
  #nod02.vm.synced_folder ".", "/"
  end 
config.vm.provider "virtualbox" do |v| 
  v.memory = 1024
  v.cpus = 1 
  end 
end
