# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update; apt-get install -y shellcheck curl apache2 

tee /etc/apache2/sites-enabled/000-default.conf >/dev/null <<EOF
<VirtualHost *:80>
	ServerName example.org
	ServerAdmin webmaster@example.org
	DocumentRoot /var/www/html/

        RedirectMatch 404 .*.htsh
        ErrorDocument 404 /404.html


        <Location /assets/>
          AllowOverride none
          Options -Indexes
          Require all granted
        </Location>

        <Location /cgi-bin/>
          AuthFormProvider file
          AuthType form
          AuthName "Reserved Area"
          Session On
          SessionCookieName session path=/
          SessionCryptoPassphrase secret
          SessionMaxAge 36000
          require valid-user

          # This is the login page
          ErrorDocument 401 /login.html

          # This is the file containing users login data
          AuthUserFile /var/www/html/.htpasswd

          ErrorDocument 401 "<html><meta http-equiv=\"refresh\" content=\"0;url=/login.htm\"></html>"
        </Location>

        <Directory /var/www/html/>
          AuthFormProvider file
          AuthType form
          AuthName "Reserved Area"
          Session On
          SessionCookieName session path=/
          SessionCryptoPassphrase secret
          SessionMaxAge 36000
          require valid-user

          # This is the login page
          ErrorDocument 401 /login.html

          # This is the file containing users login data
          AuthUserFile /var/www/html/.htpasswd
        </Directory>

        <Location "/logout">
          SetHandler form-logout-handler
          AuthFormLogoutLocation "/logged-out"
          Session on
          SessionCookieName session path=/
          SessionMaxAge 1
        </Location>

        RewriteEngine On
        RewriteRule /index /cgi-bin/index.cgi [NC,PT]
        RewriteRule /index.html /cgi-bin/index.cgi [NC,PT]  
        RewriteRule /foo /cgi-bin/foo.cgi [NC,PT]
        RewriteRule /logged-out /assets/logout.html [NC,PT]



	ErrorLog /var/log/apache2/error.log
	CustomLog /var/log/apache2/access.log combined
	Include conf-available/serve-cgi-bin.conf
</VirtualHost>
EOF
a2enmod cgid
a2enmod auth_form
a2enmod request
a2enmod session
a2enmod session_cookie
a2enmod session_crypto
a2enmod rewrite

service apache2 restart
echo "########################"
echo "# http://localhost:8101"
SCRIPT

Vagrant.configure("2") do |config|
config.vm.define "form" do |form|
  form.vm.hostname = "form"
  form.vm.box = "ubuntu/bionic64"
  form.vm.provision "shell", inline: $script
  form.vm.network "forwarded_port", guest: 80, host: 8101
  form.vm.synced_folder ".", "/var/www/html"
  end
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
  end
end
